models:
  response_model: # 回答模型的环境变量
    model_name: MODEL_NAME # 所用模型的名称
    base_url: MODEL_BASE_URL # 所用模型的转发地址
    api_key: MODEL_API_KEY # 所用的api_key的环境变量名称
  
  embed_model: # 嵌入模型的环境变了
    model_name: EMBED_NAME
    base_url: EMBED_BASE_URL
    api_key: EMBED_API_KEY


database: # 数据库环境变量
  URL : DATABASE_URL
  USER : DATABASE_USER
  PASSWORD : DATABASE_PASSWORD
  NAME : DATABASE_NAME