models:
  response_model: # 用于回答的模型
    model_name: Qwen/Qwen3-32B # 所用模型的名称
    base_url: https://api-inference.modelscope.cn/v1/ # 所用模型的转发地址
    api_key_name: MODELSCOPE_API_KEY # 所用的api_key的环境变量名称
  
  embed_model: # 用于嵌入的模型
    model_name: m3e-base
    base_url: http://localhost:9997/v1
    api_key_name: null


database:
  URL : "neo4j://192.168.130.19:7688"
  USER : "neo4j"
  PASSWORD : "neo4j123!!"
  NAME : "neo4j"